### ISSUE TITLE
can't find file 'mime' 

### ISSUE THREAD

**Issue by codenoid** [vladfaust/tele.cr#2]
i just clone the git, set TOKEN, do crystal build example/bot.cr, then i got this message
```
in src/tele/client.cr:6: while requiring "mime": can't find file 'mime' relative to '/folder/hobby/hiro/src/tele'

require "mime"
```

**Comment by vladfaust** [comment]
@codenoid You have to run `crystal deps update` in the project folder :+1:

**Comment by codenoid** [comment]
thanks ^^
